### ISSUE TITLE
inclusion of ``Float64MultiArray()``

### ISSUE THREAD

**Issue by huckl3b3rry87** [jdlangs/RobotOS.jl#27]
I noticed that the package is not tested for [Float64MultiArray()](https://github.com/jdlangs/RobotOS.jl/blob/master/test/typegeneration.jl)

I assume that there is a way around this type, but the following commands seemed to work in previous versions of julia and now they do not:
```
using RobotOS
@rosimport std_msgs.msg: Float64MultiArray
Float64MultiArray()
```
with the error:
```
ERROR: UndefVarError: Float64MultiArray not defined
```
Is there an easy way around using this type of data structure? Or is it easy to add this functionality?

Thanks!

**Comment by jdlangs** [comment]
Hi, I think it's working fine. It looks like you just forgot a couple of key commands:
```
julia> using RobotOS

julia> @rosimport std_msgs.msg: Float64MultiArray

julia> rostypegen()

julia> using std_msgs.msg

julia> Float64MultiArray()
std_msgs.msg.Float64MultiArray(std_msgs.msg.MultiArrayLayout(std_msgs.msg.MultiArrayDimension[], 0x00000000), Float64[])
```
It would not have ever worked before without the `rostypegen()` command so maybe those lines were somehow deleted in your code?

**Comment by huckl3b3rry87** [comment]
Thank you!!
