### ISSUE TITLE
How to use dynamic reconfigure in julia ros?

### ISSUE THREAD

**Issue by xonez** [jdlangs/RobotOS.jl#35]
Any API for dynamic reconfigure? Thanks!

**Comment by jdlangs** [comment]
Hi @xonez, the scope of this package does not include wrapping APIs provided by various ROS packages. (e.g., dynamic_reconfigure, tf, etc.). It is quite easy to call those python APIs using `PyCall` directly though. The only extra step you'll need to take is that anywhere the python library expects a ROS message object, convert it to a `PyObject` first. Just doing `PyObject(my_ros_message)` should work fine.
