### ISSUE TITLE
Cannot publish any kind of message

### ISSUE THREAD

**Issue by gstavrinos** [jdlangs/RobotOS.jl#53]
While working on a pick and place wrapper for MoveIt, I noticed that my messages were not published. At first I thought that there was a problem with my code or MoveIt, but I created a simple node and still cannot publish a message. My (simple) node is the following:

```
#!/usr/bin/env julia
using RobotOS
@rosimport geometry_msgs.msg: PoseStamped
rostypegen()
using geometry_msgs.msg
init_node("julia_test")
t = Publisher("/test_topic", PoseStamped, queue_size = 1)
sleep(5)
ps = PoseStamped()
ps.header.stamp = RobotOS.now()

i = 1

while i < 10
    publish(t, ps)
    println("Published"*string(i))
    sleep(1)
    i += 1
end
```

Any thoughts?

**Comment by jdlangs** [comment]
I think your problem is you are calling Julia's `sleep` which is not allowing rospy to do the message publishing. Try using `rossleep` instead or calling `sleep` with a `Duration` instance.

**Comment by gstavrinos** [comment]
Just tried it, but the problem persists. I will wait for the julia-1.0 compatibility update, and update the issue here.

**Comment by gstavrinos** [comment]
Latest version of RobotOS  with Julia-1.0.1 seems to be working. I can publish messages normally. The issue #57 regarding services, persists.

Thanks for the update, Josh! I am closing this.
