### ISSUE TITLE
ROS Unregister

### ISSUE THREAD

**Issue by pinhofst** [jdlangs/RobotOS.jl#91]
Hello,

Is the subscriber method `unregister` that allows one to unpublish/unsubscribe from a topic supported in RobotOS? I am using version 0.4.3.

Awesome package - thanks!

**Comment by jdlangs** [comment]
Not sure if this is still of interest but fyi any `rospy` function can be easily called using `PyCall` and the underlying [PyObject](https://github.com/jdlangs/RobotOS.jl/blob/master/src/pubsub.jl#L44)
