### ISSUE TITLE
`ResourceNotFound('rosgraph')`

### ISSUE THREAD

**Issue by lassepe** [jdlangs/RobotOS.jl#94]
I tried to run the [Full Example](https://jdlangs.github.io/RobotOS.jl/latest/#full-example) from the docs but I cannot initialize a node since it fails with

```julia
julia> main()
ERROR: PyError ($(Expr(:escape, :(ccall(#= /home/lassepe/.julia/packages/PyCall/3fwVL/src/pyfncall.jl:43 =# @pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, pyargsptr, kw))))) <class 'rospkg.common.ResourceNotFound'>
ResourceNotFound('rosgraph')
  File "/home/lassepe/.julia/conda/3/lib/python3.9/site-packages/rospy/client.py", line 309, in init_node
    rospy.core.configure_logging(resolved_node_name)
  File "/home/lassepe/.julia/conda/3/lib/python3.9/site-packages/rospy/core.py", line 405, in configure_logging
    _log_filename = rosgraph.roslogging.configure_logging('rospy', level, filename=filename)
  File "/home/lassepe/.julia/conda/3/lib/python3.9/site-packages/rosgraph/roslogging.py", line 156, in configure_logging
    rosgraph_d = rospkg.RosPack().get_path('rosgraph')
  File "/home/lassepe/.julia/conda/3/lib/python3.9/site-packages/rospkg/rospack.py", line 207, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
```

Am I missing any setup steps? I have a clean system (with no ros installed system-wide). I installed the ros dependencies through `Conda.jl` using

```julia
Conda.add("ros-rospy"; channel = "conda-forge")
Conda.add("ros-geometry-msgs"; channel = "conda-forge")
```

I also tried installing `ros-rosgraph` directly, hoping that this would fix the issue but that left me with the same error.

**Comment by mattborghi** [comment]
I had the same issue when I was trying to make the tests work. So I installed `rosgraph` and reopened `roscore` and everything worked.

**Comment by jdlangs** [comment]
It is almost certain the problem is with the ROS packages being installed via conda and not this package. I would expect you will see the same error if you try to run a ROS python script in the same environment. In general, the ROS environment should be set up and tested with python code before trying to do anything with this package.
